import 'package:flutter_test/flutter_test.dart';
import 'package:secure_shell_go/services/socks5.dart';

/// The bytes in this file are written out by hand rather than built from the
/// constants they are testing — a fixture that is generated by the code under
/// test would agree with it however wrong both were. They are the examples
/// from RFC 1928, and what `curl --socks5` actually puts on the wire.
void main() {
  group('greeting', () {
    test('parses the ordinary no-auth greeting', () {
      final greeting = Socks5Greeting.parse([0x05, 0x01, 0x00]);
      expect(greeting.methods, [0x00]);
      expect(greeting.offersNoAuth, isTrue);
    });

    test('parses a multi-method greeting and finds no-auth among them', () {
      // What curl sends when it has been given a proxy user: no-auth first,
      // then username/password.
      final greeting = Socks5Greeting.parse([0x05, 0x02, 0x00, 0x02]);
      expect(greeting.methods, [0x00, 0x02]);
      expect(greeting.offersNoAuth, isTrue);
    });

    test('a client that will not go unauthenticated is recognised', () {
      final greeting = Socks5Greeting.parse([0x05, 0x02, 0x01, 0x02]);
      expect(greeting.offersNoAuth, isFalse);
    });

    test('rejects a SOCKS4 client rather than half-answering it', () {
      expect(
        () => Socks5Greeting.parse([0x04, 0x01, 0x00]),
        throwsA(isA<Socks5FormatException>()),
      );
    });

    test('rejects a truncated greeting', () {
      expect(
        () => Socks5Greeting.parse([0x05]),
        throwsA(isA<Socks5FormatException>()),
      );
      expect(
        () => Socks5Greeting.parse([0x05, 0x03, 0x00]),
        throwsA(isA<Socks5FormatException>()),
      );
    });
  });

  group('method selection', () {
    test('accepting no-auth is exactly two bytes', () {
      expect(socks5MethodSelection(Socks5.methodNoAuth), [0x05, 0x00]);
    });

    test('refusing is 0xFF, which is a complete legal answer', () {
      expect(socks5MethodSelection(Socks5.methodNone), [0x05, 0xFF]);
    });
  });

  group('request parsing', () {
    test('CONNECT to an IPv4 address', () {
      final request = Socks5Request.parse([
        0x05, 0x01, 0x00, 0x01, // VER CONNECT RSV IPv4
        192, 168, 1, 10, //         DST.ADDR
        0x1F, 0x90, //              DST.PORT 8080
      ]);

      expect(request.isConnect, isTrue);
      expect(request.addressType, Socks5.addressIpv4);
      expect(request.host, '192.168.1.10');
      expect(request.port, 8080);
    });

    test('CONNECT to a domain name', () {
      final request = Socks5Request.parse([
        0x05, 0x01, 0x00, 0x03, // VER CONNECT RSV DOMAIN
        0x0B, //                    length
        ...'example.com'.codeUnits,
        0x00, 0x50, //              DST.PORT 80
      ]);

      expect(request.addressType, Socks5.addressDomain);
      expect(request.host, 'example.com');
      expect(request.port, 80);
    });

    test('CONNECT to an IPv6 address', () {
      final request = Socks5Request.parse([
        0x05, 0x01, 0x00, 0x04, // VER CONNECT RSV IPv6
        0x20, 0x01, 0x0D, 0xB8, //  2001:0db8:…
        0x00, 0x00, 0x00, 0x00,
        0x00, 0x00, 0x00, 0x00,
        0x00, 0x00, 0x00, 0x01,
        0x01, 0xBB, //              DST.PORT 443
      ]);

      expect(request.addressType, Socks5.addressIpv6);
      expect(request.host, '2001:0db8:0000:0000:0000:0000:0000:0001');
      expect(request.port, 443);
    });

    test('the highest port survives being read as unsigned', () {
      final request = Socks5Request.parse([
        0x05, 0x01, 0x00, 0x01,
        127, 0, 0, 1,
        0xFF, 0xFF,
      ]);
      expect(request.port, 65535);
    });

    test('a BIND request parses, and is not a CONNECT', () {
      final request = Socks5Request.parse([
        0x05, 0x02, 0x00, 0x01, // BIND
        127, 0, 0, 1,
        0x00, 0x50,
      ]);
      expect(request.isConnect, isFalse);
      expect(request.command, 0x02);
    });

    test('rejects a truncated address and a truncated port', () {
      expect(
        () => Socks5Request.parse([0x05, 0x01, 0x00, 0x01, 127, 0]),
        throwsA(isA<Socks5FormatException>()),
      );
      expect(
        () => Socks5Request.parse([0x05, 0x01, 0x00, 0x01, 127, 0, 0, 1, 0x00]),
        throwsA(isA<Socks5FormatException>()),
      );
    });

    test('rejects an unknown address type', () {
      expect(
        () => Socks5Request.parse([0x05, 0x01, 0x00, 0x09, 0, 0]),
        throwsA(isA<Socks5FormatException>()),
      );
    });
  });

  group('address lengths', () {
    test('are fixed except for a domain, where the first byte is the length',
        () {
      expect(socks5AddressLength(Socks5.addressIpv4, 0), 4);
      expect(socks5AddressLength(Socks5.addressIpv6, 0), 16);
      expect(socks5AddressLength(Socks5.addressDomain, 11), 12);
    });

    test('an unknown type has no length to guess at', () {
      expect(
        () => socks5AddressLength(0x09, 0),
        throwsA(isA<Socks5FormatException>()),
      );
    });

    test('the longest possible request is the domain case', () {
      expect(
        4 + socks5AddressLength(Socks5.addressDomain, 255) + 2,
        Socks5.maxRequestBytes,
      );
    });
  });

  group('replies', () {
    test('success is ten bytes ending in an all-zero IPv4 bind address', () {
      expect(socks5Reply(Socks5.replySucceeded), [
        0x05, 0x00, 0x00, 0x01,
        0, 0, 0, 0,
        0, 0,
      ]);
    });

    test('a failure differs from success in exactly one byte', () {
      final ok = socks5Reply(Socks5.replySucceeded);
      final unreachable = socks5Reply(Socks5.replyHostUnreachable);

      expect(unreachable[1], 0x04);
      expect(unreachable.length, ok.length);
      for (var i = 0; i < ok.length; i++) {
        if (i == 1) continue;
        expect(unreachable[i], ok[i], reason: 'byte $i should not differ');
      }
    });

    test('the refusals the proxy actually sends', () {
      expect(socks5Reply(Socks5.replyCommandNotSupported)[1], 0x07);
      expect(socks5Reply(Socks5.replyAddressNotSupported)[1], 0x08);
      expect(socks5Reply(Socks5.replyGeneralFailure)[1], 0x01);
    });
  });

  group('address decoding', () {
    test('IPv4 is dotted quad', () {
      expect(socks5DecodeAddress(Socks5.addressIpv4, [10, 0, 0, 255]),
          '10.0.0.255');
    });

    test('a domain drops its length prefix', () {
      expect(
        socks5DecodeAddress(Socks5.addressDomain, [3, ...'foo'.codeUnits]),
        'foo',
      );
    });

    test('IPv6 is written out in full, uncompressed', () {
      expect(
        socks5DecodeAddress(Socks5.addressIpv6, List<int>.filled(16, 0)),
        '0000:0000:0000:0000:0000:0000:0000:0000',
      );
    });
  });
}
