import 'dart:io';

import 'package:flutter_test/flutter_test.dart';
import 'package:secure_shell_go/models/host.dart';
import 'package:secure_shell_go/services/known_hosts_service.dart';
import 'package:secure_shell_go/services/ssh_service.dart';

/// Exercises the paths that do not need a live SSH server: private key
/// parsing (which happens before any socket work) and socket error mapping.
///
/// The key fixtures are generated by `ssh-keygen` in [_generateKeys], so these
/// assertions run against real OpenSSH output rather than hand-written blobs.
void main() {
  late Directory tempDir;
  late SshService service;
  late Map<String, String> keys;

  setUpAll(() async {
    tempDir = await Directory.systemTemp.createTemp('ssh_service_test');
    keys = await _generateKeys(tempDir);
  });

  tearDownAll(() async {
    if (await tempDir.exists()) await tempDir.delete(recursive: true);
  });

  setUp(() {
    service = SshService(
      knownHosts: KnownHostsService(
        file: File('${tempDir.path}/known_hosts.json'),
      ),
    );
  });

  Host host({
    String hostname = '127.0.0.1',
    int port = 1,
    SshAuthMethod authMethod = SshAuthMethod.privateKey,
  }) {
    return Host(
      id: 'test',
      label: 'test',
      hostname: hostname,
      port: port,
      username: 'nobody',
      authMethod: authMethod,
    );
  }

  Future<SshConnectionException> failure(
    Host h,
    SshCredentials credentials,
  ) async {
    try {
      final connection = await service.connect(
        host: h,
        credentials: credentials,
        verifyHostKey: (_) async => true,
        timeout: const Duration(seconds: 5),
      );
      connection.close();
      fail('expected connect() to throw');
    } on SshConnectionException catch (e) {
      return e;
    }
  }

  group('private key parsing', () {
    // A key that parses cleanly gets past _parseIdentities and dies at the
    // socket instead — port 1 is closed, so "connection refused" is proof the
    // key itself was accepted.
    for (final name in const [
      'ed25519_plain',
      'rsa_plain',
      'rsa_pem',
      'ecdsa_plain',
    ]) {
      test('$name parses and reaches the network', () async {
        final error = await failure(
          host(),
          SshCredentials(privateKeyPem: keys[name]),
        );
        expect(error.message, contains('refused'));
      });
    }

    for (final name in const ['ed25519_enc', 'rsa_enc']) {
      test('$name unlocks with the right passphrase', () async {
        final error = await failure(
          host(),
          SshCredentials(privateKeyPem: keys[name], passphrase: 'hunter2'),
        );
        expect(error.message, contains('refused'));
      });

      test('$name reports a missing passphrase', () async {
        final error = await failure(
          host(),
          SshCredentials(privateKeyPem: keys[name]),
        );
        expect(error.message, contains('passphrase-protected'));
      });

      test('$name reports a wrong passphrase', () async {
        final error = await failure(
          host(),
          SshCredentials(privateKeyPem: keys[name], passphrase: 'wrong'),
        );
        expect(error.message, contains('Check the passphrase'));
      });
    }

    test('garbage is rejected with a readable message', () async {
      final error = await failure(
        host(),
        const SshCredentials(privateKeyPem: 'not a key at all'),
      );
      expect(error.message, contains('does not look like a private key'));
    });

    test('an empty key is rejected before touching the network', () async {
      final error = await failure(host(), const SshCredentials());
      expect(error.message, contains('Paste a private key'));
    });
  });

  group('error mapping', () {
    test('a closed port reads as "connection refused"', () async {
      final error = await failure(
        host(authMethod: SshAuthMethod.password),
        const SshCredentials(password: 'x'),
      );
      expect(error.message, contains('refused'));
      expect(error.message, contains('port 1'));
    });

    test('an unresolvable name reads as "could not find a host"', () async {
      final error = await failure(
        host(
          hostname: 'no-such-host.invalid',
          port: 22,
          authMethod: SshAuthMethod.password,
        ),
        const SshCredentials(password: 'x'),
      );
      expect(error.message, contains('Could not find a host'));
    });

    test('a missing password is caught before connecting', () async {
      final error = await failure(
        host(authMethod: SshAuthMethod.password),
        const SshCredentials(),
      );
      expect(error.message, contains('Enter a password'));
    });
  });

  /// Every case here fails while resolving the chain, which happens before a
  /// socket is opened — so they assert on the connect path proper without
  /// needing a bastion to talk to.
  group('jump hosts', () {
    Host via(String? jumpHostId, {String id = 'target'}) => Host(
          id: id,
          label: 'Prod DB',
          hostname: '127.0.0.1',
          port: 1,
          username: 'nobody',
          authMethod: SshAuthMethod.password,
          jumpHostId: jumpHostId,
        );

    SshService serviceWith(List<Host> hosts) {
      final byId = {for (final host in hosts) host.id: host};
      return SshService(
        knownHosts: KnownHostsService(
          file: File('${tempDir.path}/known_hosts.json'),
        ),
        jumpHosts: JumpHostResolver(
          lookupHost: (id) async => byId[id],
          loadCredentials: (_) async => const SshCredentials(password: 'x'),
        ),
      );
    }

    Future<SshConnectionException> connectFailure(
      SshService svc,
      Host target,
    ) async {
      try {
        final connection = await svc.connect(
          host: target,
          credentials: const SshCredentials(password: 'x'),
          verifyHostKey: (_) async => true,
          timeout: const Duration(seconds: 5),
        );
        connection.close();
        fail('Expected the connect to fail.');
      } on SshConnectionException catch (e) {
        return e;
      }
    }

    test('a host set to jump via itself is refused by name', () async {
      final target = via('target');
      final error = await connectFailure(serviceWith([target]), target);
      expect(error.message, contains('via itself'));
      expect(error.message, contains('Prod DB'));
    });

    test('a loop is refused rather than recursing forever', () async {
      final target = via('bastion');
      final bastion = Host(
        id: 'bastion',
        label: 'Bastion',
        hostname: '127.0.0.1',
        port: 1,
        username: 'nobody',
        authMethod: SshAuthMethod.password,
        jumpHostId: 'target',
      );
      final error = await connectFailure(
        serviceWith([target, bastion]),
        target,
      );
      expect(error.message, contains('loop'));
    });

    test('a deleted jump host names the host that still points at it',
        () async {
      final target = via('gone');
      final error = await connectFailure(serviceWith([target]), target);
      expect(error.message, contains('no longer exists'));
      expect(error.message, contains('Prod DB'));
    });

    // Silently connecting direct would send the traffic somewhere the user
    // deliberately configured it not to go.
    test('a configured jump host with no resolver refuses to connect direct',
        () async {
      final error = await failure(
        via('bastion'),
        const SshCredentials(password: 'x'),
      );
      expect(error.message, contains('jump host'));
      expect(error.message, isNot(contains('Connection refused')));
    });

    test('a chain failure is a plain connection error, so it is not retried '
        'as if it were a dropped network', () async {
      final target = via('target');
      final error = await connectFailure(serviceWith([target]), target);
      expect(error, isNot(isA<JumpHostException>()));
      expect(error, isNot(isA<SshAuthenticationException>()));
    });

    test('a jump host with no saved credentials is an auth failure, which '
        'reconnect must not retry', () async {
      // Resolves fine, then fails on the hop's missing credential. The hop
      // is unreachable here, so this asserts the type ordering only.
      final svc = SshService(
        knownHosts: KnownHostsService(
          file: File('${tempDir.path}/known_hosts.json'),
        ),
        jumpHosts: JumpHostResolver(
          lookupHost: (id) async => Host(
            id: id,
            label: 'Bastion',
            hostname: '127.0.0.1',
            port: 1,
            username: 'nobody',
            authMethod: SshAuthMethod.password,
          ),
          loadCredentials: (_) async => null,
        ),
      );
      final error = await connectFailure(svc, via('bastion'));
      // Port 1 refuses first, so this is the unreachable-jump message; what
      // matters is that it is attributed to the jump, not to the target.
      expect(error, isA<JumpHostException>());
      expect(
        (error as JumpHostException).phase,
        JumpHostPhase.unreachable,
      );
      expect(error.jumpHost.displayName, 'Bastion');
      expect(error.message, contains('jump host'));
    });
  });

  group('agent auth', () {
    test('an agent host fails clearly instead of crashing', () async {
      final error = await failure(
        host(authMethod: SshAuthMethod.agent),
        const SshCredentials(),
      );
      // Either "no agent running" or the dartssh2 limitation, depending on
      // whether the machine running the suite happens to have an agent — both
      // are clear, and neither is a crash or a hang.
      expect(error.message, isNotEmpty);
      expect(
        error.message,
        anyOf(
          contains('No SSH agent found'),
          contains('SSH agent'),
        ),
      );
    });
  });

  group('a name lookup that failed', () {
    Host hostNamed(String hostname) => Host(
          id: 'h1',
          label: '',
          hostname: hostname,
          port: 22,
          username: 'root',
          authMethod: SshAuthMethod.password,
        );

    const lookupFailure = SocketException(
      'Failed host lookup',
      osError: OSError('Name or service not known', -2),
    );

    test('names the embedded port instead of blaming the spelling', () {
      // The record the owner ended up with: the whole `host:port` went into
      // the hostname, and the generic advice was misleading — the spelling
      // was fine and it was already an IP address.
      final message = describeSocketError(
        lookupFailure,
        hostNamed('127.0.0.1:22303'),
      );
      expect(message, contains('22303'));
      expect(message, contains('Port'));
      expect(message, isNot(contains('spelling')));
    });

    test('keeps the generic advice for an ordinary name', () {
      final message = describeSocketError(
        lookupFailure,
        hostNamed('nosuchhost.example'),
      );
      expect(message, contains('nosuchhost.example'));
      expect(message, contains('spelling'));
    });

    test('a bare IPv6 literal is not mistaken for one', () {
      final message = describeSocketError(lookupFailure, hostNamed('fe80::1'));
      expect(message, contains('spelling'));
    });
  });
}

Future<Map<String, String>> _generateKeys(Directory dir) async {
  const specs = <String, List<String>>{
    'ed25519_plain': ['-t', 'ed25519', '-N', ''],
    'ed25519_enc': ['-t', 'ed25519', '-N', 'hunter2'],
    'rsa_plain': ['-t', 'rsa', '-b', '2048', '-N', ''],
    'rsa_enc': ['-t', 'rsa', '-b', '2048', '-N', 'hunter2'],
    'rsa_pem': ['-t', 'rsa', '-b', '2048', '-m', 'PEM', '-N', ''],
    'ecdsa_plain': ['-t', 'ecdsa', '-N', ''],
  };

  final result = <String, String>{};
  for (final entry in specs.entries) {
    final path = '${dir.path}/${entry.key}';
    final process = await Process.run(
      'ssh-keygen',
      [...entry.value, '-f', path, '-C', 'test', '-q'],
    );
    if (process.exitCode != 0) {
      throw StateError('ssh-keygen failed: ${process.stderr}');
    }
    result[entry.key] = await File(path).readAsString();
  }
  return result;
}
