import 'dart:io';

import 'package:flutter_test/flutter_test.dart';
import 'package:secure_shell_go/models/host.dart';
import 'package:secure_shell_go/services/known_hosts_service.dart';
import 'package:secure_shell_go/services/ssh_service.dart';

/// Exercises the paths that do not need a live SSH server: private key
/// parsing (which happens before any socket work) and socket error mapping.
///
/// The key fixtures are generated by `ssh-keygen` in [_generateKeys], so these
/// assertions run against real OpenSSH output rather than hand-written blobs.
void main() {
  late Directory tempDir;
  late SshService service;
  late Map<String, String> keys;

  setUpAll(() async {
    tempDir = await Directory.systemTemp.createTemp('ssh_service_test');
    keys = await _generateKeys(tempDir);
  });

  tearDownAll(() async {
    if (await tempDir.exists()) await tempDir.delete(recursive: true);
  });

  setUp(() {
    service = SshService(
      knownHosts: KnownHostsService(
        file: File('${tempDir.path}/known_hosts.json'),
      ),
    );
  });

  Host host({
    String hostname = '127.0.0.1',
    int port = 1,
    SshAuthMethod authMethod = SshAuthMethod.privateKey,
  }) {
    return Host(
      id: 'test',
      label: 'test',
      hostname: hostname,
      port: port,
      username: 'nobody',
      authMethod: authMethod,
    );
  }

  Future<SshConnectionException> failure(
    Host h,
    SshCredentials credentials,
  ) async {
    try {
      final connection = await service.connect(
        host: h,
        credentials: credentials,
        verifyHostKey: (_) async => true,
        timeout: const Duration(seconds: 5),
      );
      connection.close();
      fail('expected connect() to throw');
    } on SshConnectionException catch (e) {
      return e;
    }
  }

  group('private key parsing', () {
    // A key that parses cleanly gets past _parseIdentities and dies at the
    // socket instead — port 1 is closed, so "connection refused" is proof the
    // key itself was accepted.
    for (final name in const [
      'ed25519_plain',
      'rsa_plain',
      'rsa_pem',
      'ecdsa_plain',
    ]) {
      test('$name parses and reaches the network', () async {
        final error = await failure(
          host(),
          SshCredentials(privateKeyPem: keys[name]),
        );
        expect(error.message, contains('refused'));
      });
    }

    for (final name in const ['ed25519_enc', 'rsa_enc']) {
      test('$name unlocks with the right passphrase', () async {
        final error = await failure(
          host(),
          SshCredentials(privateKeyPem: keys[name], passphrase: 'hunter2'),
        );
        expect(error.message, contains('refused'));
      });

      test('$name reports a missing passphrase', () async {
        final error = await failure(
          host(),
          SshCredentials(privateKeyPem: keys[name]),
        );
        expect(error.message, contains('passphrase-protected'));
      });

      test('$name reports a wrong passphrase', () async {
        final error = await failure(
          host(),
          SshCredentials(privateKeyPem: keys[name], passphrase: 'wrong'),
        );
        expect(error.message, contains('Check the passphrase'));
      });
    }

    test('garbage is rejected with a readable message', () async {
      final error = await failure(
        host(),
        const SshCredentials(privateKeyPem: 'not a key at all'),
      );
      expect(error.message, contains('does not look like a private key'));
    });

    test('an empty key is rejected before touching the network', () async {
      final error = await failure(host(), const SshCredentials());
      expect(error.message, contains('Paste a private key'));
    });
  });

  group('error mapping', () {
    test('a closed port reads as "connection refused"', () async {
      final error = await failure(
        host(authMethod: SshAuthMethod.password),
        const SshCredentials(password: 'x'),
      );
      expect(error.message, contains('refused'));
      expect(error.message, contains('port 1'));
    });

    test('an unresolvable name reads as "could not find a host"', () async {
      final error = await failure(
        host(
          hostname: 'no-such-host.invalid',
          port: 22,
          authMethod: SshAuthMethod.password,
        ),
        const SshCredentials(password: 'x'),
      );
      expect(error.message, contains('Could not find a host'));
    });

    test('a missing password is caught before connecting', () async {
      final error = await failure(
        host(authMethod: SshAuthMethod.password),
        const SshCredentials(),
      );
      expect(error.message, contains('Enter a password'));
    });
  });
}

Future<Map<String, String>> _generateKeys(Directory dir) async {
  const specs = <String, List<String>>{
    'ed25519_plain': ['-t', 'ed25519', '-N', ''],
    'ed25519_enc': ['-t', 'ed25519', '-N', 'hunter2'],
    'rsa_plain': ['-t', 'rsa', '-b', '2048', '-N', ''],
    'rsa_enc': ['-t', 'rsa', '-b', '2048', '-N', 'hunter2'],
    'rsa_pem': ['-t', 'rsa', '-b', '2048', '-m', 'PEM', '-N', ''],
    'ecdsa_plain': ['-t', 'ecdsa', '-N', ''],
  };

  final result = <String, String>{};
  for (final entry in specs.entries) {
    final path = '${dir.path}/${entry.key}';
    final process = await Process.run(
      'ssh-keygen',
      [...entry.value, '-f', path, '-C', 'test', '-q'],
    );
    if (process.exitCode != 0) {
      throw StateError('ssh-keygen failed: ${process.stderr}');
    }
    result[entry.key] = await File(path).readAsString();
  }
  return result;
}
